---

- hosts: all
  become: true
  tasks:

  - name: install httpd and vim packages (CentOS)
    yum:
      name:
        - httpd
        - vim
        - ncdu
    when: ansible_distribution == "CentOS"

  - name: install apache2 and vim packages (Ubuntu)
    apt:
      name:
        - apache2
        - vim
        - ncdu
        - btop
    when: ansible_distribution in ["Debian","Ubuntu"]

