---

- hosts: all
  become: true
  tasks:

  - name: install httpd and vim packages
    yum:
      name:
        - httpd
        - vim
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 and vim packages
    apt:
      name:
        - apache2
        - vim
      update_cache: yes
    when: ansible_distribution in ["Debian","Ubuntu"]

