---

- hosts: all
  become: true
  tasks:

  - name: remove http and vim packages
    yum:
      name:
       - httpd
       - vim
      state: absent
    when: ansible_distribution == "CentOS"

  - name: remove apache2 and vim packages
    apt:
       name: 
         - apache2
         - vim
       state: absent
    when: ansible_distribution in ["Debian","Ubuntu"]

