---

- name: Remove packages from servers
  hosts: all
  become: true
  tasks:

  - name: remove http and vim packages CentOS
    yum:
      name:
       - httpd
       - vim
       - btop
       - mariadb
       - php
       - samba
       - ncdu
      state: absent
    when: ansible_distribution == "CentOS"

  - name: remove apache2 and vim packages Ubuntu
    apt:
       name: 
         - apache2
         - vim
         - mariadb-server
         - samba
         - htop
         - php   
         - ncdu
       state: absent
    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: remove dependecies from Centos
    yum:
      autoremove: true
    when: ansible_distribution == "CentOS"
 
  - name: remove dependecies from Ubuntu
    apt:
     autoremove: true
    when: ansible_distribution in ["Debian","Ubuntu"]    
