---

- hosts: all
  become: true
  tasks:

   - name: install updates (CentOS)
     yum:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "CentOS"
    
   - name: install updates (Ubuntu)
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution in ["Debian","Ubuntu"]

- hosts: web_servers
  become: true
  tasks:

   - name: install httpd and php for CentOS servers (CentOS)
     yum:
       name:
        - httpd
        - php
       state: latest
     when: ansible_distribution == "CentOS"

   - name: install apache2 and php for Ubuntu servers
     apt:
        name:
         - apache2
         - libapache2-mod-php
        state: latest
     when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package (CentOS)
      yum:
        name:
          - mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package (Ubuntu)
      apt:
        name:
          - mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package for CentOS and Ubuntu servers
      package:
        name:
          - samba
        state: latest 
