---

- hosts: all
  become: true
  tasks:

   - name: install updates (CentOS)
     tags: always
     yum:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "CentOS"
    
   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution in ["Debian","Ubuntu"]

- hosts: web_servers
  become: true
  tasks:

   - name: install httpd and php for CentOS servers (CentOS)
     tags: centos,httpd,php,web-servers
     yum:
       name:
        - httpd
        - php
       state: latest
     when: ansible_distribution == "CentOS"

   - name: install apache2 and php for Ubuntu servers
     tags: ubuntu,apache2,apache,php,web-servers
     apt:
        name:
         - apache2
         - libapache2-mod-php
        state: latest
     when: ansible_distribution == "Ubuntu"
   
   - name: copy default html file for site
     tags: copy,file,site,httpd,apache,apache2
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644


- hosts: db_servers
  become: true
  tasks:

    - name: install mariadb package (CentOS)
      tags: centos,db,mariadb
      yum:
        name:
          - mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package (Ubuntu)
      tags: ubuntu,db,mariadb
      apt:
        name:
          - mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

    - name: install samba package for CentOS and Ubuntu servers
      tags: samba,file-servers
      package:
        name:
          - samba
        state: latest 
