---

- hosts: all
  become: true
  tasks:

  - name: update repository index for CentOS servers
    yum:
     update_only: yes
     update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: update repository index for Ubuntu servers
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
